/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FirstGradleWithSpringBoot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Library {

    public static void main(String a[]) {
    	SpringApplication.run(Library.class, a);
    	for(int numberValue=0;numberValue<10;numberValue++) {
    		System.out.println(numberValue);
    	}
    }
    
}
